import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavBar from "./navbar";
import Landing from "./landing";
import About from "./about";
import Techs from "./technologies";
import Contact from "./contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script async src="https://kit.fontawesome.com/19d668566d.js" crossOrigin="anonymous"></script>
      </Head>
      <main className="bg-white h-screen mx-auto font-roboto">
        <div className="fixed top-0 w-screen">
          <NavBar />
        </div>
        <div id="landing">
          <Landing />
        </div>
        <div className="my-36 " id="about" >
          <h1 className="text-center text-3xl my-32">Learn More</h1>
          <div className="flex flex-wrap justify-around">
            <About />
            <Techs />
          </div>
        </div>
        <Contact />
      </main>
    </>
  );
}
